name = "akqc"
compatibility_date = "2025-07-17"

# Pages 프로젝트 설정
pages_build_output_dir = "public"

# D1 데이터베이스 바인딩
[[d1_databases]]
binding = "DB"
database_name = "akqc-db"
database_id = "fda5f281-1ab4-4cef-9609-895fbb0c2899"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "akqc-files"

